# k8s/dockerhub_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOmlicmFoaW1taW50YWwiLCJwYXNzd29yZCI6ImRja3JfcGF0X0hMXzJfdzgySVFzTFNlQzRBQlBnWFo3Y1hzYyIsImVtYWlsIjoiaWJyYWhpbS5
