# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins
#   namespace: jenkins
#   labels:
#     app: jenkins
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins
#   template:
#     metadata:
#       labels:
#         app: jenkins
#     spec:
#       nodeSelector:
#         node-role: jenkins-node
#       serviceAccountName: jenkins-sa
#       securityContext:
#         fsGroup: 1000
#         runAsUser: 1000
#       containers:
#         - name: jenkins
#           image: mohfathy/jenkins-with-docker-kubectl-awscli
#           ports:
#             - containerPort: 8080
#             - containerPort: 50000
#           livenessProbe:
#             httpGet:
#               path: "/login"
#               port: 8080
#             initialDelaySeconds: 90
#             periodSeconds: 10
#           readinessProbe:
#             httpGet:
#               path: "/login"
#               port: 8080
#             initialDelaySeconds: 60
#             periodSeconds: 10
#           volumeMounts:
#             - name: jenkins-home
#               mountPath: /var/jenkins_home
#       volumes:
#         - name: jenkins-home
#           persistentVolumeClaim:
#             claimName: jenkins-home-pvc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      nodeSelector:
        "node-role": "jenkins-node"
      imagePullSecrets:
        - name: regcred      # <-- Added for DockerHub authentication
      containers:
        - name: jenkins
          image: mohfathy/jenkins-with-docker-kubectl-awscli
          ports:
            - containerPort: 8080
            - containerPort: 50000

          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home-pvc
